### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-1-evaluacion-final-celiarodriguezmo#1]
Muy buen trabajo @celiarodriguezmo!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header { height: 100vh }`, `.header { background-position: center }`, `.header { height: 100vh }`, `.header { background-position: center }`
- [x] CSS > FOOTER: La separación entre los enlaces no es la correcta.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack al coordinador de Adalab.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by celiarodriguezmo** [comment]
done
